//This file is automatically generated. DO NOT EDIT!
package experimental.create;
import java.util.*;
import com.robotraconteur.*;
public interface async_Create
{
    void async_get_DistanceTraveled(Action2<Integer,RuntimeException> rr_handler, int rr_timeout);
    void async_set_DistanceTraveled(int value, Action1<RuntimeException> rr_handler, int rr_timeout);
    void async_get_AngleTraveled(Action2<Integer,RuntimeException> rr_handler, int rr_timeout);
    void async_set_AngleTraveled(int value, Action1<RuntimeException> rr_handler, int rr_timeout);
    void async_get_Bumpers(Action2<UnsignedByte,RuntimeException> rr_handler, int rr_timeout);
    void async_set_Bumpers(UnsignedByte value, Action1<RuntimeException> rr_handler, int rr_timeout);
    void async_Drive(short velocity, short radius,Action1<RuntimeException> rr_handler,int rr_timeout);
    void async_StartStreaming(Action1<RuntimeException> rr_handler,int rr_timeout);
    void async_StopStreaming(Action1<RuntimeException> rr_handler,int rr_timeout);
}

