//This file is automatically generated. DO NOT EDIT!
package experimental.createwebcam2;
import java.util.*;
import com.robotraconteur.*;
@RobotRaconteurServiceObjectInterface
public interface Webcam
{
    String get_Name();
    WebcamImage CaptureFrame();
    void StartStreaming();
    void StopStreaming();
    WebcamImage_size CaptureFrameToBuffer();
    Pipe<WebcamImage> get_FrameStream();
    void set_FrameStream(Pipe<WebcamImage> value);
    ArrayMemory<UnsignedBytes> get_buffer();
    MultiDimArrayMemory<UnsignedBytes> get_multidimbuffer();
}

