//This file is automatically generated. DO NOT EDIT!
package experimental.createwebcam2;
import java.util.*;
import com.robotraconteur.*;
public class WebcamHost_default_impl implements WebcamHost{
    protected Map<Integer,String> rrvar_WebcamNames;
    public Map<Integer,String> get_WebcamNames() { return rrvar_WebcamNames; }
    public void set_WebcamNames(Map<Integer,String> value) { rrvar_WebcamNames = value; }
    public Webcam get_Webcams(int ind) {
    throw new UnsupportedOperationException();
    }
}
