//This file is automatically generated. DO NOT EDIT!
package experimental.createwebcam;
import java.util.*;
import com.robotraconteur.*;
public interface async_WebcamHost
{
    void async_get_WebcamNames(Action2<Map<Integer,String>,RuntimeException> rr_handler, int rr_timeout);
    void async_set_WebcamNames(Map<Integer,String> value, Action1<RuntimeException> rr_handler, int rr_timeout);
    void async_get_Webcams(int ind, Action2<Webcam,RuntimeException> handler, int timeout);
}

