//This file is automatically generated. DO NOT EDIT!
package experimental.createwebcam;
import java.util.*;
import com.robotraconteur.*;
public class Webcam_skel extends ServiceSkel {
    protected Webcam obj;
    public Webcam_skel(Object o) { 
    super(o);
    obj=(Webcam)o;
    }
    public void releaseCastObject() { 
    obj=null;
    super.releaseCastObject();
    }
    public MessageElement callGetProperty(String membername) {
    if(membername.equals( "Name"))
    {
    String ret=obj.get_Name();
    return MessageElementUtil.newMessageElementDispose("return",ret);
    }
    throw new MemberNotFoundException("Member not found");
    }
    public void callSetProperty(String membername, MessageElement m) {
    if(membername.equals( "Name"))
    {
    obj.set_Name(MessageElementUtil.<String>castDataAndDispose(m));
    return;
    }
    throw new MemberNotFoundException("Member not found");
    }
    public MessageElement callFunction(String rr_membername, vectorptr_messageelement rr_m) {
    if(rr_membername.equals( "CaptureFrame"))
    {
    WebcamImage rr_ret=obj.CaptureFrame();
    return MessageElementUtil.newMessageElementDispose("return",RobotRaconteurNode.s().packStructure(rr_ret));
    }
    if(rr_membername.equals( "StartStreaming"))
    {
    this.obj.StartStreaming();
    return new MessageElement("return",new int[] {0});
    }
    if(rr_membername.equals( "StopStreaming"))
    {
    this.obj.StopStreaming();
    return new MessageElement("return",new int[] {0});
    }
    if(rr_membername.equals( "CaptureFrameToBuffer"))
    {
    WebcamImage_size rr_ret=obj.CaptureFrameToBuffer();
    return MessageElementUtil.newMessageElementDispose("return",RobotRaconteurNode.s().packStructure(rr_ret));
    }
    throw new MemberNotFoundException("Member not found");
    }
    public Object getSubObj(String name, String ind) {
    throw new MemberNotFoundException("");
    }
    public void registerEvents(Object obj1) {
    obj=(Webcam)obj1;
    }
    public void unregisterEvents(Object obj1) {
    obj=(Webcam)obj1;
    }
    public Object getCallbackFunction(long endpoint, String membername) {
    throw new MemberNotFoundException("Member not found");
    }
    public  void initPipeServers(Object obj1) {
    obj=(Webcam)obj1;
    obj.set_FrameStream(new Pipe<WebcamImage>(innerskel.getPipe("FrameStream")));
    }
    public void initCallbackServers(Object obj1) {
    obj=(Webcam)obj1;
    }
    public void initWireServers(Object obj1) {
    obj=(Webcam)obj1;
    }
    public WrappedArrayMemoryDirector getArrayMemory(String name) {
    if(name.equals( "buffer")) {
    WrappedArrayMemoryDirectorNET<UnsignedBytes> dir=new  WrappedArrayMemoryDirectorNET<UnsignedBytes>(obj.get_buffer());
    return dir;
    }
    throw new MemberNotFoundException("Member Not Found");
    }
    public WrappedMultiDimArrayMemoryDirector getMultiDimArrayMemory(String name) {
    if(name.equals( "multidimbuffer")) {
    WrappedMultiDimArrayMemoryDirectorNET<UnsignedBytes> dir=new  WrappedMultiDimArrayMemoryDirectorNET<UnsignedBytes>(obj.get_multidimbuffer());
    return dir;
    }
    throw new MemberNotFoundException("Member Not Found");
    }
    public String getRRType() { return "experimental.createwebcam.Webcam"; }
}
