//This file is automatically generated. DO NOT EDIT!
package experimental.createwebcam;
import java.util.*;
import com.robotraconteur.*;
public class WebcamHost_skel extends ServiceSkel {
    protected WebcamHost obj;
    public WebcamHost_skel(Object o) { 
    super(o);
    obj=(WebcamHost)o;
    }
    public void releaseCastObject() { 
    obj=null;
    super.releaseCastObject();
    }
    public MessageElement callGetProperty(String membername) {
    if(membername.equals( "WebcamNames"))
    {
    Map<Integer,String> ret=obj.get_WebcamNames();
    return MessageElementUtil.newMessageElementDispose("return",RobotRaconteurNode.s().<Integer,String>packMapType(ret,Integer.class,String.class));
    }
    throw new MemberNotFoundException("Member not found");
    }
    public void callSetProperty(String membername, MessageElement m) {
    if(membername.equals( "WebcamNames"))
    {
    obj.set_WebcamNames((Map<Integer,String>)RobotRaconteurNode.s().<Integer,String>unpackMapTypeDispose(m.getData()));
    return;
    }
    throw new MemberNotFoundException("Member not found");
    }
    public MessageElement callFunction(String rr_membername, vectorptr_messageelement rr_m) {
    throw new MemberNotFoundException("Member not found");
    }
    public Object getSubObj(String name, String ind) {
    if(name.equals( "Webcams")) {
    return obj.get_Webcams(Integer.valueOf(ind));
    }
    throw new MemberNotFoundException("");
    }
    public void registerEvents(Object obj1) {
    obj=(WebcamHost)obj1;
    }
    public void unregisterEvents(Object obj1) {
    obj=(WebcamHost)obj1;
    }
    public Object getCallbackFunction(long endpoint, String membername) {
    throw new MemberNotFoundException("Member not found");
    }
    public  void initPipeServers(Object obj1) {
    obj=(WebcamHost)obj1;
    }
    public void initCallbackServers(Object obj1) {
    obj=(WebcamHost)obj1;
    }
    public void initWireServers(Object obj1) {
    obj=(WebcamHost)obj1;
    }
    public WrappedArrayMemoryDirector getArrayMemory(String name) {
    throw new MemberNotFoundException("Member Not Found");
    }
    public WrappedMultiDimArrayMemoryDirector getMultiDimArrayMemory(String name) {
    throw new MemberNotFoundException("Member Not Found");
    }
    public String getRRType() { return "experimental.createwebcam.WebcamHost"; }
}
