//This file is automatically generated. DO NOT EDIT!
package experimental.createwebcam;
import java.util.*;
import com.robotraconteur.*;
@RobotRaconteurServiceObjectInterface
public interface WebcamHost
{
    Map<Integer,String> get_WebcamNames();
    void set_WebcamNames(Map<Integer,String> value);
    Webcam get_Webcams(int ind);
}

