//This file is automatically generated. DO NOT EDIT!
package experimental.createwebcam2;
import java.util.*;
import com.robotraconteur.*;
public class WebcamImage implements RRStructure
{
    public int width;
    public int height;
    public int step;
    public UnsignedBytes data;
}

