//This file is automatically generated. DO NOT EDIT!
package experimental.createwebcam2;
import java.util.*;
import com.robotraconteur.*;
@RobotRaconteurServiceObjectInterface
public interface WebcamHost
{
    Map<Integer,String> get_WebcamNames();
    Webcam get_Webcams(int ind);
}

