//This file is automatically generated. DO NOT EDIT!
package experimental.create2;
import java.util.*;
import com.robotraconteur.*;
public class SensorPacket implements RRStructure
{
    public UnsignedByte ID;
    public UnsignedBytes Data;
}

