//This file is automatically generated. DO NOT EDIT!
package experimental.create2;
import java.util.*;
import com.robotraconteur.*;
public class Create_default_impl implements Create{
    protected Callback<Func2<Integer,Integer,UnsignedBytes>> rrvar_play_callback;
    protected WireBroadcaster<SensorPacket> rrvar_packets;
    protected int rrvar_DistanceTraveled;
    public int get_DistanceTraveled() { return rrvar_DistanceTraveled; }
    public void set_DistanceTraveled(int value) { rrvar_DistanceTraveled = value; }
    protected int rrvar_AngleTraveled;
    public int get_AngleTraveled() { return rrvar_AngleTraveled; }
    public void set_AngleTraveled(int value) { rrvar_AngleTraveled = value; }
    protected UnsignedByte rrvar_Bumpers;
    public UnsignedByte get_Bumpers() { return rrvar_Bumpers; }
    public void set_Bumpers(UnsignedByte value) { rrvar_Bumpers = value; }
    public void Drive(short velocity, short radius) {
    throw new UnsupportedOperationException();    }
    public void StartStreaming() {
    throw new UnsupportedOperationException();    }
    public void StopStreaming() {
    throw new UnsupportedOperationException();    }
    protected  Vector<Action> rrvar_Bump=new Vector<Action>();
    public void  addBumpListener(Action listener) {
    synchronized(rrvar_Bump) {
    rrvar_Bump.add(listener);
    }
    }
    public void  removeBumpListener(Action listener) {
    synchronized(rrvar_Bump) {
    rrvar_Bump.remove(listener);
    }
    }
    public Callback<Func2<Integer,Integer,UnsignedBytes>> get_play_callback()
    { return rrvar_play_callback;  }
    public void set_play_callback(Callback<Func2<Integer,Integer,UnsignedBytes>> value)
    {
    if (rrvar_play_callback!=null) throw new IllegalStateException("Callback already set");
    rrvar_play_callback= value;
    }
    public Wire<SensorPacket> get_packets()
    { return rrvar_packets.getWire();  }
    public void set_packets(Wire<SensorPacket> value)
    {
    if (rrvar_packets!=null) throw new IllegalStateException("Pipe already set");
    rrvar_packets= new WireBroadcaster<SensorPacket>(value);
    }
}
