//This file is automatically generated. DO NOT EDIT!
package experimental.create2;
import java.util.*;
import com.robotraconteur.*;
class experimental__create2Constants 
{
    public static class Create
    {
    public static final short DRIVE_STRAIGHT=32767;
    public static final short SPIN_CLOCKWISE=-1;
    public static final short SPIN_COUNTERCLOCKWISE=1;
    }
}
