//This file is automatically generated. DO NOT EDIT!
package experimental.createwebcam;
import java.util.*;
import com.robotraconteur.*;
public class WebcamImage_size
{
    public int width;
    public int height;
    public int step;
}

