//This file is automatically generated. DO NOT EDIT!
package experimental.createwebcam;
import java.util.*;
import com.robotraconteur.*;
public class WebcamHost_stub extends ServiceStub implements WebcamHost, async_WebcamHost {
    public WebcamHost_stub(WrappedServiceStub innerstub) {
        super(innerstub); 
    }
    public Map<Integer,String> get_WebcamNames() {
    return (Map<Integer,String>)RobotRaconteurNode.s().<Integer,String>unpackMapTypeDispose(rr_innerstub.propertyGet("WebcamNames").getData());
    }
    public void set_WebcamNames(Map<Integer,String> value) {
    MessageElement m=null;
    try {
    m=MessageElementUtil.newMessageElementDispose("value",RobotRaconteurNode.s().<Integer,String>packMapType(value,Integer.class,String.class));
    rr_innerstub.propertySet("WebcamNames", m);
    }
    finally {
    if (m!=null) m.delete();
    }
    }
    public void dispatchEvent(String rr_membername, vectorptr_messageelement rr_m) {
    }
    public Webcam get_Webcams(int ind) {
    return (Webcam)findObjRefTyped("Webcams",String.valueOf(ind),"experimental.createwebcam.Webcam");
    }
    public MessageElement callbackCall(String rr_membername, vectorptr_messageelement rr_m) {
    throw new MemberNotFoundException("Member not found");
    }
    public void async_get_WebcamNames(Action2<Map<Integer,String>,RuntimeException> rr_handler, int rr_timeout)
    {
    rr_async_PropertyGet("WebcamNames",new rrend_async_get_WebcamNames(),rr_handler,rr_timeout);
    }
    protected class rrend_async_get_WebcamNames implements Action3<MessageElement,RuntimeException,Object> {
    public void action(MessageElement value ,RuntimeException err,Object param)
    {
    Action2<Map<Integer,String>,RuntimeException> rr_handler=(Action2<Map<Integer,String>,RuntimeException>)param;
    if (err!=null)
    {
    rr_handler.action(null,err);
    return;
    }
    Map<Integer,String> rr_ret;
    try {
    rr_ret=(Map<Integer,String>)RobotRaconteurNode.s().<Integer,String>unpackMapTypeDispose(value.getData());
    } catch (RuntimeException err2) {
    rr_handler.action(null,err2);
    return;
    }
    rr_handler.action(rr_ret,null);
    }
    }
    public void async_set_WebcamNames(Map<Integer,String> value, Action1<RuntimeException> rr_handler, int rr_timeout)
    {
    MessageElement m=null;
    try {
    m=MessageElementUtil.newMessageElementDispose("value",RobotRaconteurNode.s().<Integer,String>packMapType(value,Integer.class,String.class));
    rr_async_PropertySet("WebcamNames",m,new rrend_async_set_WebcamNames(),rr_handler,rr_timeout);
    }
    finally {
    if (m!=null) m.delete();
    }
    }
    protected class rrend_async_set_WebcamNames implements Action3<MessageElement,RuntimeException,Object> {
    public void action(MessageElement m ,RuntimeException err,Object param)
    {
    Action1<RuntimeException> rr_handler=(Action1<RuntimeException>)param;
    if (err!=null)
    {
    rr_handler.action(err);
    return;
    }
    rr_handler.action(null);
    }
    }
    public void async_get_Webcams(int ind, Action2<Webcam,RuntimeException> handler, int timeout) {
    asyncFindObjRefTyped("Webcams",String.valueOf(ind),"experimental.createwebcam.Webcam",handler,timeout);
    }
}
