//This file is automatically generated. DO NOT EDIT!
package experimental.create;
import java.util.*;
import com.robotraconteur.*;
public class SensorPacket
{
    public UnsignedByte ID;
    public UnsignedBytes Data;
}

